Repository CSID-DGU/2023-2-OSSProj-ZIIO-4, pull requests merged in 2023-12, with the labels that each got.

#49 [Feat] 액세스 토큰 scope 수정, 공지사항 관련 변경사항
  backend/src/main/java/com/ziio/backend/config/handler/OAuthLoginSuccessHandler.java
  backend/src/main/java/com/ziio/backend/controller/NoticeController.java
  backend/src/main/java/com/ziio/backend/crawler/CrawlerManager.java
  backend/src/main/java/com/ziio/backend/service/CategoryService.java
  backend/src/main/java/com/ziio/backend/service/NoticeService.java
  backend/src/main/resources/application.properties
  docker-compose.yml
Labels: bug, enhancement

#50 [Feat] 공지사항 및 크롤링 변경 사항 반영 및 즐겨찾기(북마크) API 구현
  backend/src/main/java/com/ziio/backend/config/SecurityConfig.java
  backend/src/main/java/com/ziio/backend/config/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/ziio/backend/controller/BookMarkController.java
  backend/src/main/java/com/ziio/backend/controller/CategoryController.java
  backend/src/main/java/com/ziio/backend/controller/NoticeController.java
  backend/src/main/java/com/ziio/backend/crawler/CollegeAndDepartmentWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/crawler/CrawlerManager.java
  backend/src/main/java/com/ziio/backend/crawler/EtcWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/crawler/MainWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/dto/BookMarkDTO.java
  backend/src/main/java/com/ziio/backend/dto/MyPageDTO.java
  backend/src/main/java/com/ziio/backend/dto/NoticeDTO.java
  backend/src/main/java/com/ziio/backend/entity/BookMark.java
  backend/src/main/java/com/ziio/backend/entity/MyPage.java
  backend/src/main/java/com/ziio/backend/entity/Notice.java
  backend/src/main/java/com/ziio/backend/exception/DuplicateRecordException.java
  backend/src/main/java/com/ziio/backend/repository/BookMarkRepository.java
  backend/src/main/java/com/ziio/backend/repository/CategoryRepository.java
  backend/src/main/java/com/ziio/backend/repository/MyPageRepository.java
  backend/src/main/java/com/ziio/backend/repository/NoticeRepository.java
  backend/src/main/java/com/ziio/backend/service/BookMarkService.java
  backend/src/main/java/com/ziio/backend/service/CategoryService.java
  backend/src/main/java/com/ziio/backend/service/MyPageService.java
  backend/src/main/java/com/ziio/backend/service/NoticeService.java
  backend/src/main/resources/import.sql
Labels: bug, enhancement

#51 [Feat] 마이페이지 API 구현
  backend/src/main/java/com/ziio/backend/config/SecurityConfig.java
  backend/src/main/java/com/ziio/backend/controller/MyPageController.java
  backend/src/main/java/com/ziio/backend/dto/MyPageDTO.java
  backend/src/main/java/com/ziio/backend/entity/MyPage.java
  backend/src/main/java/com/ziio/backend/repository/MyPageRepository.java
  backend/src/main/java/com/ziio/backend/service/MyPageService.java
Labels: enhancement

#68 [Fix, Feat] 프론트엔드 연동, 에러 해결
  backend/src/main/java/com/ziio/backend/Application.java
  backend/src/main/java/com/ziio/backend/config/SecurityConfig.java
  backend/src/main/java/com/ziio/backend/config/handler/OAuthLoginSuccessHandler.java
  backend/src/main/java/com/ziio/backend/controller/ScrapController.java
  backend/src/main/java/com/ziio/backend/crawler/CrawlerManager.java
  backend/src/main/java/com/ziio/backend/service/MyPageService.java
Labels: bug, enhancement

#70 [Style] URL 변경
  backend/src/main/java/com/ziio/backend/config/SecurityConfig.java
  backend/src/main/java/com/ziio/backend/config/handler/OAuthLoginSuccessHandler.java
Labels: enhancement

#72 [Style] RDS 데이터베이스 가용 영역 변경으로 인한 MySQL 호스트 수정
  backend/src/main/java/com/ziio/backend/crawler/CrawlerManager.java
  backend/src/main/resources/application.properties
Labels: enhancement

#73 [Style] 도커 컴포즈 데이터소스 URL 수정
  docker-compose.yml
Labels: bug

#75 [feat] bugfix
  frontend/src/api/noticeAPI.js
  frontend/src/api/schoolCalendarAPI.js
  frontend/src/api/userAPI.js
  frontend/src/components/Pagging/Pagging.jsx
  frontend/src/components/Pagging/Pagging.module.scss
  frontend/src/pages/MainNotice/MainNotice.jsx
  frontend/src/pages/MainNotice/MainNotice.module.scss
  frontend/src/pages/MainNotice/components/ClipModal/ClipModal.jsx
  frontend/src/pages/MainNotice/components/ClipModal/ClipModal.module.scss
  frontend/src/pages/MainNotice/components/NoticeItem/NoticeItem.jsx
  frontend/src/pages/MainNotice/components/NoticeItem/NoticeItem.module.scss
  frontend/src/pages/MainNotice/components/Pagging/Pagging.jsx
  frontend/src/pages/MainNotice/components/Pagging/Pagging.module.scss
  frontend/src/pages/MainNotice/components/UserCategory/UserCategory.jsx
  frontend/src/pages/MainNotice/components/UserCategory/UserCategory.module.scss
  frontend/src/pages/SchoolCalendar/SchoolCalendar.jsx
  frontend/src/pages/SchoolCalendar/components/EventList.jsx
  frontend/src/utils/category.js
Labels: bug

#78 [FEAT] bugfix
  frontend/src/pages/MainNotice/MainNotice.jsx
Labels: bug

#82 [Feat, Fix] 도메인 연결 및 프론트엔드와 배포 완료 & IT 융합교육센터 크롤링 및 테이블 교체 기능 추가
  backend/src/main/java/com/ziio/backend/config/SecurityConfig.java
  backend/src/main/java/com/ziio/backend/config/handler/OAuthLoginSuccessHandler.java
  backend/src/main/java/com/ziio/backend/constants/CrawlingInfos.java
  backend/src/main/java/com/ziio/backend/controller/StatusCheckController.java
  backend/src/main/java/com/ziio/backend/crawler/AcademicCalendarWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/crawler/CollegeAndDepartmentWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/crawler/CrawlerManager.java
  backend/src/main/java/com/ziio/backend/crawler/DiceWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/crawler/EtcWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/crawler/MainWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/entity/NewCategory.java
  backend/src/main/java/com/ziio/backend/entity/NewNotice.java
  backend/src/main/java/com/ziio/backend/repository/NewCategoryRepository.java
  backend/src/main/java/com/ziio/backend/repository/NewNoticeRepository.java
  backend/src/main/java/com/ziio/backend/service/CategoryService.java
  backend/src/main/java/com/ziio/backend/service/NoticeService.java
  backend/src/main/java/com/ziio/backend/service/TableSwitchService.java
  backend/src/main/resources/application.properties
Labels: bug, enhancement

#88 [Style, Feat] 카테고리 관련 수정사항
  backend/src/main/java/com/ziio/backend/config/SecurityConfig.java
  backend/src/main/java/com/ziio/backend/constants/CrawlingInfos.java
  backend/src/main/java/com/ziio/backend/crawler/CollegeAndDepartmentWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/crawler/EtcWebsiteCrawler.java
  backend/src/main/java/com/ziio/backend/crawler/MainWebsiteCrawler.java
Labels: enhancement
